insQuire/urls.py
from django.urls import path
from django.utils.text import slugify
from insQuire import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'insQuire'

urlpatterns = [
    path('', views.index, name='index'),
    path('categories/', views.categories, name='all_categories'),
    path('categories/<slug:slugifiedName>/', views.category, name='category'),
    path('categories/question/<int:questionID>/', views.question, name='question'),
    path('search/', views.search, name='search'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('askquestion/', views.askQuestion, name='askQuestion'),
    path('answerquestion/<int:questionID>/', views.ansQuestion, name='answerQuestion'),
    path('answerquestionhtml/<int:questionID>/', views.ansQuestionhtml, name='answerQuestionhtml'),
    path('categories/question/upvote/', views.upvote1, name='upvote1'),
    path('categories/question/downvote/', views.downvote1, name='downvote1'),
    path('answerQuestion/', views.ansQuestion, name='answerQuestion'),
    path('profile/', views.profile, name='profile'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

insQuire_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from insQuire import views
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('', views.index, name='index'),
    path('insQuire/', include('insQuire.urls')), # Maps all URLs starting with insQuire/ to the insQuire app
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

insQuire/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
    

#Helper model classes
class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    occurrences = models.IntegerField(default=0)

def __str__(self):
    return self.name

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='profile_images', blank=True, default='profile_images/default.jpg')
    website = models.URLField(blank=True)
                                      
    def __str__(self):
        return self.user.username


#The below models are related to displaying questions and answers on the website
class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.TextField()
    questionCount = models.IntegerField(default=0)
    slugifiedName = models.SlugField(max_length=50, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def save(self, *args, **kwargs):
        self.slugifiedName = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

class Question(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    dateAsked = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(UserProfile, on_delete=models.CASCADE, default=1)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    votes = models.IntegerField(default=0)

        
    def __str__(self):
        return self.title
    
class Answer(models.Model):
    content = models.TextField()
    dateAnswered = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(UserProfile, on_delete=models.CASCADE, default=1)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.content
    

insQuire/forms.py
from django import forms
from django.contrib.auth.models import User
from insQuire.models import UserProfile, Question, Answer

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture',)



class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'content', 'category']

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']

insQuire/views.py
import json
from django.shortcuts import render
from insQuire.models import Category, Question, UserProfile
from django.db import models
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from django.urls import reverse
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from insQuire.forms import QuestionForm, AnswerForm, UserForm, UserProfileForm
from django.views.decorators.csrf import csrf_exempt

def index(request):
    context = {}

    try:
        recent_questions = Question.objects.order_by('-dateAsked')[:10]
        popular_questions = Question.objects.order_by('-votes')[:10]
        context['recent_questions'] = recent_questions
        context['popular_questions'] = popular_questions
    except Question.DoesNotExist:
        context['recent_questions'] = None
        context['popular_questions'] = None

    return render(request, 'insQuire/index.html', context)

def categories(request):
    context = {}

    try:
        categories = Category.objects.all()
        context['categories'] = categories

    except Category.DoesNotExist:
        context['categories'] = None

    return render(request, 'insQuire/categories.html', context)

def category(request, slugifiedName):
    context = {}

    try:
        category = Category.objects.get(slugifiedName=slugifiedName)
        questions = Question.objects.filter(category=category)
        context['category'] = category
        context['questions'] = questions

    except Category.DoesNotExist:
        context['category'] = None
        context['questions'] = None

    return render(request, 'insQuire/category.html', context)

def question(request, questionID):
    context = {}

    try:
        question = Question.objects.get(id=questionID)
        context['question'] = question  

    except Question.DoesNotExist:
        context['question'] = None

    return render(request, 'insQuire/question.html', context)

def search(request):
    context = {}

    if request.method == 'POST':
        query = request.POST['search_bar']
        questions = Question.objects.filter(title__icontains=query)
        context['questions'] = questions
        context['query'] = query

    return render(request, 'insQuire/search.html', context)

def register(request):
    context = {}
    next_url = '/'
    registered = False
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            
            # Saving the users details. Password has to be handled different as set_password hashes it, meaning it can't be used to authenticate after being saved.
            user = user_form.save(commit=False)
            plain_password = user_form.cleaned_data['password'] 
            user.set_password(plain_password)
            user.save()

            # Upon making the new account, logging the user in
            user = authenticate(username=user.username, password=plain_password)
            login(request, user)

            profile = profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True

            # Once registered and sign in, return back to the page they were on (given by the 'next' passed in from the register template, else redirect to '/' (index) page
            next_url = request.POST.get('next', '/')
            return redirect(next_url)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
        next_url = request.GET.get('next', '/')
        
    context = {'user_form': user_form, 'profile_form': profile_form, 'registered': registered, 'next': next_url}
    return render(request, 'insQuire/register.html', context)


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('insQuire:index'))
            else:
                return render(request, 'insQuire/login.html', {'error_message': 'Your account has been disabled.'})
        else:
            print(f"Invalid login details: {username}, {password}")
            return render(request, 'insQuire/login.html', {'error_message': 'Invalid login details.'})
    else:
        return render(request, 'insQuire/login.html')

@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('insQuire:index'))

@login_required
def askQuestion(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            user_profile = request.user.userprofile
            question.author = user_profile
            question.save()
            return redirect('insQuire:index')
    else:
        form = QuestionForm()
    categories = Category.objects.all()
    return render(request, 'insQuire/askQuestion.html', {'form': form, 'categories': categories})

@login_required
def ansQuestion(request, questionID):
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():   
            question = Question.objects.get(id=questionID)
            categorySlugifiedName = question.category.slugifiedName
            user = request.user.userprofile
            answer = form.save(commit=False)
            answer.question = question
            answer.author = user
            answer.save()
            return redirect(reverse('insQuire:category', args=[categorySlugifiedName]))
    else:
        form = AnswerForm()
    return render(request, 'insQuire/answerQuestion.html', {'form': form})

@login_required
def ansQuestionhtml(request, questionID):
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():   
            question = Question.objects.get(id=questionID)
            user = request.user.userprofile
            answer = form.save(commit=False)
            answer.question = question
            answer.author = user
            answer.save()
            return redirect(reverse('insQuire:question', args=[questionID]))
    else:
        form = AnswerForm()
    return render(request, 'insQuire/answerQuestion.html', {'form': form})



@csrf_exempt
def upvote1(request):
    if request.method == 'POST':
        quesID = json.loads(request.body)
        question = Question.objects.get(id=quesID['question_id'])
        question.votes += 1
        question.save()
        return JsonResponse({'votes': question.votes})
    
@csrf_exempt
def downvote1(request):
    if request.method == 'POST':
        quesID = json.loads(request.body)
        question = Question.objects.get(id=quesID['question_id'])
        question.votes -= 1
        question.save()
        return JsonResponse({'votes': question.votes})

def profile(request):
    user_profile = request.user.userprofile  # Retrieve the UserProfile instance for the current user
    user_posts = Question.objects.filter(author=user_profile)  # Filter questions by the user's UserProfile instance
    context = {
        'user_profile': user_profile,
        'user_posts': user_posts,
    }
    return render(request, 'insQuire/profile.html', context)


    

templates/insQuire/add_category.html
{% extends 'insQuire/base.html' %}

{% block title_block %}
    Add Category - InsQuire
{% endblock %}

{% block main_block %}
    <div class="container mt-5">
        <h1>Add Category</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

templates/insQuire/askQuestion.html
{% extends 'insQuire/base.html' %}
{% load static %}

{% block title_block %}
    Ask a Question - InsQuire
{% endblock %}

{% block main_block %}
    <div class="container mt-5">
        <h1>Ask a Question</h1>
        <!--form for asking questions-->
        <form method="post">
            {% csrf_token %}
            <!--input for question titles-->
            <div class="mb-3">
                <label for="id_title" class="form-label">Question Title:</label>
                <input type="text" class="form-control" id="id_title" name="title" required>
            </div>
            <!--input for question content-->
            <div class="mb-3">
                <label for="id_content" class="form-label">Question Content:</label>
                <textarea class="form-control" id="id_content" name="content" rows="5" required></textarea>
            </div>
            <!--input to select category-->
            <div class="mb-3">
                <label for="id_category" class="form-label">Select a category for your question:</label>
                <select class="form-select" id="id_category" name="category" required>
                    <option value="" selected disabled>Select a category</option>
                    <!--listing all categories-->
                    {% for category in categories %}
                        <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>
            
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

templates/insQuire/base.html
<!DOCTYPE html>
{% load static %}
{% load django_bootstrap5 %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap imports. If these are causing errors for you, make sure you've got bootstrap installed with pip.
    $ pip install django_bootstrap5 -->
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <!-- Custom imports -->
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    {% block Import_block %}
    {% endblock %}


    <title>
        {% block title_block %}
            InsQuire
        {% endblock %}
    </title>

        <!-- Navigation bar at the top of the screen-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <span class="navbar-brand p-2 mb-0 h1">InsQuire</span>
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active"><a class="nav-link" href="{% url 'insQuire:index' %}">Home</a></li>
                    <li class="nav-item active"><a class="nav-link" href="{% url 'insQuire:all_categories' %}">Categories</a></li>
                    {% if user.is_authenticated %}
                    <li class="nav-item active"><a class="nav-link" href="{% url 'insQuire:logout' %}">Logout</a></li>
                    {% else %}
                    <li class="nav-item active"><a class="nav-link" href="{% url 'insQuire:register' %}">Sign Up</a></li>
                    <li class="nav-item active"><a class="nav-link" href="{% url 'insQuire:login' %}">Log in</a></li>
                    {% endif %}
                </ul>
            </div>
            <!--shows user info if logged in-->
            <div class="d-flex align-items-center">
                {% if user.is_authenticated %}
                <!--user profile picture-->
                    {% if user.userprofile.picture %}
                        <a href="{% url 'insQuire:profile' %}">
                            <img src="{{ user.userprofile.picture.url }}" alt="User Avatar" class="user-picture">
                        </a>
                    {% endif %}
                    <a href="{% url 'insQuire:profile' %}" class="ml-2 text-white">{{ user.username }}</a>
                {% endif %}
            </div>
            <!--search functionality in the navbar-->
            <form class="form-inline my-2 my-lg-0 d-flex" method=POST action="{% url 'insQuire:search' %}">
                {% csrf_token %}
                <input class="form-control mr-sm-2" name="search_bar" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </nav>

         <!-- Sidebar on the right side of the screen -->
    {% block sidebar_block %}

    <div class="right-sidebar">
        <div class="sidebar-item">
            {% if user.is_authenticated %}
                <p class="ask-question">Ask a Question</p>
                <a href="{% url 'insQuire:askQuestion' %}" class="ask-question-btn">Click here to ask a question</a>
            {% else %}
                <p class="ask-question">Sign Up or Log In</p>
                <a href="{% url 'insQuire:register' %}">Sign Up</a>
                <a href="{% url 'insQuire:login' %}">Log In</a>
            {% endif %}
            <hr class="sidebar-divider">
            <div class="question-box">
                <p>Trending Questions</p>
                {% if recent_questions %}
                    {% for question in recent_questions|slice:":5" %}
                        <p class="question-title">{{ forloop.counter }}. {{ question.title }}</p>
                    {% endfor %}
                {% else %}
                    <p>No recent questions found.</p>
                {% endif %}
            </div>
            <hr class="sidebar-divider">
            <div class="question-box">
                <p>Featured Questions</p>
            </div>
        </div>
    </div>
    {% endblock %} 
</head>


<body style="background-color: #E6E6E6;">
    {% block body_block %}
    <main>    
        {% block main_block %}
            <p>Content goes here </p>
        {% endblock %}
    </main>
    {% endblock %}

    <script src="{% static 'javascript/javascript.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>

</html>

templates/insQuire/category.html
{% extends 'insQuire/base.html' %}

<head>
    {% block title_block %}
        {% if category %}
            {{ category.name }} - InsQuire
        {% else %}
            Category Not Found - InsQuire
        {% endif %}
    {% endblock %}    

</head>


{% block main_block %}
{% load static %}

    <h2>{{ category.name }}</h2>

    {% if questions %}
    <div class="row">
        {% for question in questions %}
            {% if forloop.counter0|divisibleby:3 %}
                </div><div class="row">
            {% endif %}
            
            <div class="card" style="width: 18rem; margin-left: 3em ; margin-top: 3em; margin-bottom: 3em">
                <div class="card-body">
                  <h5 class="card-title">{{ question.title }}</h5>
                  <p class="card-text">author: {{ question.author|truncatewords:10 }}</p>
                  <p class="card-text">{{ question.content|truncatewords:10 }}</p>
                  <div>
                    <span class="card-text">votes: </span>
                    <span class="card-text" id="votes{{question.id}}">{{ question.votes }}</span>
                  </div>
                  <!--if user is logged in then they can vote and answer questions-->
                    {% if user.is_authenticated %}
                        <div class="btn-group-vertical">
                            <button type="button" id="upvote-button" class="btn btn-link btn-sm" onclick="upVote({{ question.id }})">
                                <img src="{% static 'pictures/upvote.png'%}" alt="Upvote" style="width = 30px; height:30px">
                            </button>
                        
                            <button type="button" id="downvote-button" class="btn btn-link btn-sm" onclick="downVote({{ question.id }})">
                                <img src="{% static "pictures/downvote.png"%}" alt="Downvote" style="width = 30px; height:30px">
                            </button>
                        </div>

                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#ansQues{{question.id}}">
                        Answer Question
                        </button>


                        <!-- Modal -->
                        <div class="modal fade" id="ansQues{{question.id}}" tabindex="-1" role="dialog" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                <h5 class="modal-title">Answer {{ question.title }}</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                </div>
                                <div class="modal-body">
                                    <!--form to subtmit answer in modal-->
                                    <form method="post" action="{% url 'insQuire:answerQuestion' question.id %}">
                                        {% csrf_token %}
                                        <div class="form-group">
                                        <label>Answer question</label>
                                        <textarea class="form-control" name="content" rows="3"></textarea>
                                        </div>
                                        <button type="submit" >Submit</button>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--if user is not logged in then they will be prompted to log in
                    if they try to press the voting buttons, they will be redirected to login page-->
                        {% else %}
                        <div>
                            <div class="alert alert-primary" role="alert">
                                Please <a href="{% url 'insQuire:login'%}" class="alert-link">Login</a> to vote or answer questions.
                            </div>

                            <button type="button" class="btn btn-link btn-sm" onclick="notLoggedIn()">
                                <div class="btn-group-vertical">
                                    <img src="{% static "pictures/upvote.png" %}" alt="Upvote" style="width = 30px; height:30px">
                                    <img src="{% static "pictures/downvote.png" %}" alt="Downvote" style="width = 30px; height:30px">
                                </div>
                            </button>
                        </div>
                        {% endif %}
                        <!--user will be able to view question no matter if they are signed in or not-->
                        <a href="{% url 'insQuire:question' question.id %}" class="card-link">
                            <button class="btn btn-primary" type="submit">View More</button>
                        </a>
                </div>
            </div> 
        {% endfor %}
    </div>
    <!--id no questions are found in the category, show the below message-->
    {% else %}
        <p>No questions found in this category.</p>
    {% endif %}
{% endblock %}

templates/insQuire/index.html
{% extends 'insQuire/base.html' %}
{% load static %}

{% block Import_block %}
<link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block title_block %}
    insQuire - Index
{% endblock %}

{% block body_block %}

    <h2>Welcome To Home Page</h2>
    <div class="container">
        <div class="row">
            <div class="col-10">
                <!--if there are recent questions, show them in the home page-->
            {% if recent_questions %}
                {% for question in recent_questions %}
                    <div class="question-card card">
                        <div class="card-body">
                            <div class="user-info text-center mb-3">
                                <!--only show profile pictire if it exist to prevent errors-->
                                {% if question.author.picture %}
                                    <img src="{{ question.author.picture.url }}" alt="User Avatar" class="user-picture rounded-circle">
                                {% endif %}
                                <!--show user information that asked question-->
                            </div>
                            <h5 class="card-title">{{ question.author.user.username }}</h5>
                            {% if question.dateAsked %}
                                <p class="text-muted" style="font-size: smaller;">Date posted: {{ question.dateAsked|date:"Y-m-d H:i:s" }}</p>
                            {% endif %}
                            <h5 class="card-title">{{ question.title }}</h5>
                            <p class="card-text">{{ question.content|truncatewords:10 }}</p>

                            <!--if user is logged in, allow them to vote-->
                            {% if user.is_authenticated %}
                                <div class="btn-group" role="group" aria-label="Question actions">
                                    
                                    <button type="button" class="btn btn-success" onclick="upVote({{ question.id }})">Upvote</button>
                                    <span class="vote-count" id="votes{{question.id}}">{{ question.votes }}</span>
                                    <button type="submit" class="btn btn-danger" onclick="downVote({{ question.id }})">Downvote</button>

                                </div>
                                <!--if not, they will be prompted to login-->
                            {% else %}
                                <div>
                                    <div class="alert alert-primary" role="alert">
                                        Please <a href="{% url 'insQuire:login'%}" class="alert-link">Login</a> to vote or answer questions.
                                    </div>
                                    <div class="btn-group" role="group" aria-label="Question actions">
                                
                                        <button type="button" class="btn btn-success" onclick="notLoggedIn()">Upvote</button>
                                        <span class="vote-count" id="votes{{question.id}}">{{ question.votes }}</span>
                                        <button type="button" class="btn btn-danger" onclick="notLoggedIn()">Downvote</button>
                
                                    </div>
                                </div>
                            {% endif %}
                                <!--user will be able to login no matter what-->
                            <a href="{% url 'insQuire:question' question.id %}" class="btn btn-primary">View Question</a>                    
                                <!--user can answer questions if logged in-->
                            {% if user.is_authenticated %}
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#ansQueshtml{{question.id}}">
                                Answer Question
                            </button>
                            {% endif %}

                            <!-- Modal -->
                            <div class="modal fade" id="ansQueshtml{{question.id}}" tabindex="-1" role="dialog" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                    <h5 class="modal-title">Answer {{ question.title }}</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    </div>
                                    <div class="modal-body">
                                        <!--form to submit answer-->
                                        <form method="post" action="{% url 'insQuire:answerQuestionhtml' question.id %}">
                                            {% csrf_token %}
                                            <div class="form-group">
                                            <label>Answer question</label>
                                            <textarea class="form-control" name="content" rows="3"></textarea>
                                            </div>
                                            <button type="submit" >Submit</button>
                                        </form>
                                    </div>
                                    <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p>No recent questions found.</p>
            {% endif %}
        </div>
    </div> 
</div>
{% endblock %}